<h2>Teacher's Rating</h2>
<hr/>
<p>
In our site we provide the opportunity to the user to assign rating to the professors of all over the world.
 As it is done by users all readers should be cautious about the Rating, and should not completely
 rely on it, because this is not the universaly accepted or offically processed "Professor's rating".
 As it is given by the users there may be some difference from the real world. 
 .All readers are encouraged to read the methodology carefully and understand it 
 completely before looking at the Professors rating lists and also assigning rating to the professors. 
 </p>
 <h3>
<p><a href="<?php echo $this->url(array('controller'=>'teachrating','action'=>'proflist'));?>"><?php echo "Teacher List"; ?></a></p>
</h3>
<h3>
<p><a href="<?php echo $this->url(array('controller'=>'teachrating','action'=>'methodology'));?>"><?php echo "Rating methodologies"; ?></a></p>
</h3>
<h3>
<p><a href="<?php echo $this->url(array('controller'=>'teachrating','action'=>'rateprof'));?>"><?php echo "assign rate to Teachers"; ?></a></p>
</h3>