<h2>Methodology:</h2>
<hr/>
<p>
To assign rating to any teacher we are only making count on the following Categories.
So from many perspective it may looks like incomplete, but as it is user provided ratings so we are
bound to keep it as simple as possible.
</p>
<h3>Category 'Post':</h3>
<br/>
<table border = 1>
<tr>
	<th><h3>count</h3></th>
	<th><h3>Post</h3></th>
	<th><h3>Score</h3></th>
</tr>
<tr>
	<td>1</td>
	<td>Full Professor</td>
	<td>30</td>
</tr>
<tr>
	<td>2</td>
	<td>Associate Professor</td>
	<td>24</td>
</tr>
<tr>
	<td>3</td>
	<td>Assistant Professor</td>
	<td>18</td>
</tr>
<tr>
	<td>4</td>
	<td>Lecturer</td>
	<td>12</td>
</tr>
</table>
<br/>
<br/>
<h3>Category 'Teaching Experience':</h3>
<br/>
<table border = 1>
<tr>
	<th><h3>count</h3></th>
	<th><h3>Time period</h3></th>
	<th><h3>Score</h3></th>
</tr>
<tr>
	<td>1</td>
	<td>More than 20 years</td>
	<td>10</td>
</tr>
<tr>
	<td>2</td>
	<td>Between 15 and 20 years</td>
	<td>8</td>
</tr>
<tr>
	<td>3</td>
	<td>Between 10 and 15 years</td>
	<td>6</td>
</tr>
<tr>
	<td>4</td>
	<td>between 3 and 10 years</td>
	<td>4</td>
</tr>
<tr>
	<td>5</td>
	<td>less than 3 years</td>
	<td>2</td>
</tr>
</table>
<br/>
<br/>
<h3>Category 'Research And Publications':</h3>
<br/>
<table border = 1>
<tr>
	<th><h3>count</h3></th>
	<th><h3>Number of publications</h3></th>
	<th><h3>Score</h3></th>
</tr>
<tr>
	<td>1</td>
	<td>More than 80</td>
	<td>30</td>
</tr>
<tr>
	<td>2</td>
	<td>Between 60 and 80 </td>
	<td>24</td>
</tr>
<tr>
	<td>3</td>
	<td>Between 40 and 60 </td>
	<td>18</td>
</tr>
<tr>
	<td>4</td>
	<td>between 20 and 40 </td>
	<td>12</td>
</tr>
<tr>
	<td>5</td>
	<td>less than 20</td>
	<td>6</td>
</tr>
</table>
<br/>
<br/>
<h3>Category 'Communication with Students':</h3>
<br/>
<table border = 1>
<tr>
	<th><h3>count</h3></th>
	<th><h3>Communication skills with the students</h3></th>
	<th><h3>Score</h3></th>
</tr>
<tr>
	<td>1</td>
	<td>Excellent</td>
	<td>30</td>
</tr>
<tr>
	<td>2</td>
	<td>Very good</td>
	<td>24</td>
</tr>
<tr>
	<td>3</td>
	<td>Good</td>
	<td>18</td>
</tr>
<tr>
	<td>4</td>
	<td>Okey</td>
	<td>12</td>
</tr>
</table>
<br/>
<p>
After assigning rating to any teacher, we gather the assigned point under each category and then simply recalculate His/her ratings by taking average
of total point(total point/number of user voted him/her).
</p>