<h2> Teachers List</h2>
<hr>
<p>The processing of this teacher's rating is completely user dependent. So there may be some difference from the real world.</p>
<br/>
<table border = 1>
<tr>
<th><h3>Rating Position</h3></th>
<th><h3>Name</h3></th>
<th><h3>University Name</h3></th>
<th><h3>Rating score</h3></th>
</tr>
<?php $i = ($this->page-1)*$this->perpage+1; ?>
<?php foreach($this->members as $member) : ?>
<tr>
<td><?php echo $i++; ?></td>
<td><a href="<?php echo $this->url(array('controller'=>'facultymember','action'=>'details', 'facultymember_id'=>$member['FacultyMemberID']));?>"><?php echo $this->escape($member['Name']); ?></a></td>
<td><?php echo $this->escape($member['uniname']);?></td>
<td><?php echo $this->escape($member['profRate']);?></td>
</tr>
<?php endforeach; ?>
</table>

<div class="post">
 <p class="links"> <?php  echo $this->members; ?> </p>
</div>
