<link rel="STYLESHEET" type="text/css" href="http://localhost/sdproject/public/codebase/dhtmlxcombo.css">
<script  src="http://localhost/sdproject/public/codebase/dhtmlxcommon.js"></script>
<script  src="http://localhost/sdproject/public/codebase/dhtmlxcombo.js"></script>
<h2>Rate your professor:</h2>
<hr/>
<form action="<?php echo $this->escape($this->form->getAction());?>" method="<?php echo $this->escape($this->form->getMethod()); ?>">
<?php echo $this->form->dropdown;?>
<br>
<h3>Category 'Post':</h3>
<br/>
<table border = 1>
<tr>
	<th><h3>count</h3></th>
	<th><h3>Post</h3></th>
	<th><h3>Score</h3></th>
</tr>
<tr>
	<td>1</td>
	<td>Full Professor</td>
	<td>30</td>
</tr>
<tr>
	<td>2</td>
	<td>Associate Professor</td>
	<td>24</td>
</tr>
<tr>
	<td>3</td>
	<td>Assistant Professor</td>
	<td>18</td>
</tr>
<tr>
	<td>4</td>
	<td>Lecturer</td>
	<td>12</td>
</tr>
</table>
<br/>
<?php echo $this->form->post;?>
<br/>
<h3>Category 'Teaching Experience':</h3>
<br/>
<table border = 1>
<tr>
	<th><h3>count</h3></th>
	<th><h3>Time period</h3></th>
	<th><h3>Score</h3></th>
</tr>
<tr>
	<td>1</td>
	<td>More than 20 years</td>
	<td>10</td>
</tr>
<tr>
	<td>2</td>
	<td>Between 15 and 20 years</td>
	<td>8</td>
</tr>
<tr>
	<td>3</td>
	<td>Between 10 and 15 years</td>
	<td>6</td>
</tr>
<tr>
	<td>4</td>
	<td>between 3 and 10 years</td>
	<td>4</td>
</tr>
<tr>
	<td>5</td>
	<td>less than 3 years</td>
	<td>2</td>
</tr>
</table>
<br>
<?php echo $this->form->experience;?>
<br/>
<h3>Category 'Research And Publications':</h3>
<br/>
<table border = 1>
<tr>
	<th><h3>count</h3></th>
	<th><h3>Number of publications</h3></th>
	<th><h3>Score</h3></th>
</tr>
<tr>
	<td>1</td>
	<td>More than 80</td>
	<td>30</td>
</tr>
<tr>
	<td>2</td>
	<td>Between 60 and 80 </td>
	<td>24</td>
</tr>
<tr>
	<td>3</td>
	<td>Between 40 and 60 </td>
	<td>18</td>
</tr>
<tr>
	<td>4</td>
	<td>between 20 and 40 </td>
	<td>12</td>
</tr>
<tr>
	<td>5</td>
	<td>less than 20</td>
	<td>6</td>
</tr>
</table>
<br/>
<?php echo $this->form->research;?>
<br/>
<h3>Category 'Communication with Students':</h3>
<br/>
<table border = 1>
<tr>
	<th><h3>count</h3></th>
	<th><h3>Communication skills with the students</h3></th>
	<th><h3>Score</h3></th>
</tr>
<tr>
	<td>1</td>
	<td>Excellent</td>
	<td>30</td>
</tr>
<tr>
	<td>2</td>
	<td>Very good</td>
	<td>24</td>
</tr>
<tr>
	<td>3</td>
	<td>Good</td>
	<td>18</td>
</tr>
<tr>
	<td>4</td>
	<td>Okey</td>
	<td>12</td>
</tr>
</table>
<br/>
<?php echo $this->form->communication;?>
<br/>
<?php echo $this->form->submit;?>
</form>
<script>
		var z=dhtmlXComboFromSelect("dropdown");
	  	z.enableFilteringMode(true);
</script>
