<h2 class="title">Ranking of Universities</h2>
<hr/>
<br/>
<p>
University rankings are inherently controversial, and no ranking is satisfying 
to all. Despite years of refinement to ranking procedures the most prominent
and widely used rankings in developed countries still generate discord and draw 
criticism. The controversy associated with rankings essentially arises from the 
question of whether the quality of universities can be precisely measured by numerical
 indicators alone.In our site we provide the opportunity to the user to assign rank to any university.
As it is done by users all readers should be cautious about the ranking, 
and should not completely rely on the ranking, because this ranking is not the universaly accepted or offically processed
"world university ranking". As it is given by the users there may be some difference
from the real world. Instead, this ranking is to be used simply as a kind of reference to assist in the decision making processes. 
All readers are encouraged to read the ranking methodology carefully and understand it completely before 
looking at the ranking lists.
</p>
<h3>
<p><a href="<?php echo $this->url(array('controller'=>'unirank','action'=>'ranklist'));?>"><?php echo "University ranklist"; ?></a></p>
</h3>
<h3>
<p><a href="<?php echo $this->url(array('controller'=>'unirank','action'=>'methodology'));?>"><?php echo "Ranking methodologies"; ?></a></p>
</h3>
<h3>
<p><a href="<?php echo $this->url(array('controller'=>'unirank','action'=>'assignrank'));?>"><?php echo "assign Rank to universities"; ?></a></p>
</h3>
