<h2>Ranking methodologies</h2>
<hr/>
<br/>
<h1>Ranking Criteria for Universities:</h1>
<br/>
<h3>Students</h3>
<table border = 1>
<tr>
	<th><h3>count</h3></th>
	<th><h3>Name of fields</h3></th>
	<th><h3>Score</h3></th>
</tr>
<tr>
	<td>1</td>
	<td>Student produced having 16 years of education</td>
	<td>2</td>
</tr>
<tr>
	<td>2</td>
	<td>Student produced having M.Phil/16 + years of education</td>
	<td>4</td>
</tr>
<tr>
	<td>3</td>
	<td>Number of Ph.D. Produced</td>
	<td>5</td>
</tr>
<tr>
	<td>4</td>
	<td>Student Selectivity</td>
	<td>6</td>
</tr>
<tr>
	<td></td>
	<td>Total:</td>
	<td>17</td>
</tr>
</table>
<br/>
<h3>Facilities</h3>
<table border = 1>
<tr>
	<th><h3>count</h3></th>
	<th><h3>Name of fields</h3></th>
	<th><h3>Score</h3></th>
</tr>
<tr>
	<td>1</td>
	<td>Number of Books/student in Main Library</td>
	<td>4</td>
</tr>
<tr>
	<td>2</td>
	<td>Number of Journals  Subscribed in the Main Library</td>
	<td>2</td>
</tr>
<tr>
	<td>3</td>
	<td>Number of Computers for Students per Student.</td>
	<td>2</td>
</tr>
<tr>
	<td>4</td>
	<td>Bandwidth per Student</td>
	<td>2</td>
</tr>
<tr>
	<td>5</td>
	<td>Labs for Practical</td>
	<td>3</td>
</tr>
<tr>
	<td>6</td>
	<td>Equipment Costing >2 million (Operational)</td>
	<td>2</td>
</tr>	
<tr>
	<td></td>
	<td>Total:</td>
	<td>15</td>
</tr>
</table>
<br/>
<h3>Finances</h3>
<table border = 1>
<tr>
	<th><h3>count</h3></th>
	<th><h3>Name of fields</h3></th>
	<th><h3>Score</h3></th>
</tr>
<tr>
	<td>1</td>
	<td>Amount Generated through Own Sources as  (% age ) of Tot. Budget</td>
	<td>2</td>
</tr>
<tr>
	<td>2</td>
	<td>Amount Spent on Library + Research as % of  Total Budget</td>
	<td>4</td>	
</tr>
<tr>
	<td>3</td>
	<td>Recurring Expenditure / Student</td>
	<td>5</td>	
</tr>
<tr>
	<td>4</td>
	<td>Non-Recurring Expenditure / Student</td>
	<td>4</td>	
</tr>
<tr>
	<td></td>
	<td>Total:</td>
	<td>15</td>
</tr>
</table>
<br/>
<h3>Facutly</h3>
<table border = 1>
<tr>
	<th><h3>count</h3></th>
	<th><h3>Name of fields</h3></th>
	<th><h3>Score</h3></th>
</tr>
<tr>
	<td>1</td>
	<td>Full Time Professors</td>
	<td>6</td>
</tr>
<tr>
	<td>2</td>
	<td>Ratio of Ph.D. Faculty to Total Faculty</td>
	<td>7</td>
</tr>
<tr>
	<td>3</td>
	<td>National & International Awards won by Faculty</td>
	<td>3</td>
</tr>
<tr>
	<td>4</td>
	<td>Student Teacher Ratio</td>
	<td>5</td>
</tr>
	<td></td>
	<td>Total:</td>
	<td>21</td>
</tr>
</table>
<br/>
<h3>Research</h3>
<table border = 1>
<tr>
	<th><h3>count</h3></th>
	<th><h3>Name of fields</h3></th>
	<th><h3>Score</h3></th>
</tr>
<tr>
<tr>
	<td>1</td>
	<td>Research Papers  / Faculty</td>
	<td>5</td>
</tr>
<tr>
<tr>
	<td>2</td>
	<td>Amount of Funds obtained through Competitive Grants for Research Projects/Faculty</td>
	<td>4</td>
</tr>
<tr>
	<td>3</td>
	<td>Number of Papers Presented and Published at Refereed National Conferences by Faculty Members and Students.</td>
	<td>5</td>
</tr>
<tr>
	<td>4</td>
	<td>Amount of Funds obtained through Competitive Grants for Research Projects/Faculty</td>
	<td>4</td>
</tr>
<tr>
	<td>5</td>
<td>Number of International Collaborative Research Projects</td>
	<td>4</td>
</tr>
<tr>
	<td>6</td>
	<td>Ph.D. Produced /Faculty</td>
	<td>3</td>
</tr>
<tr>
	<td>7</td>
	<td>Number of Research Papers Published by the Faculty Members & Students</td>
	<td>7</td>
</tr>
	<td></td>
	<td>Total:</td>
	<td>32</td>
</tr>
</table>
<br/>
<p>Each individual Category is comprised of ranking Criteria relevant to the field,
 with each assigned a number of points. The cumulative total of these points equals
 the relative weightage of the Category itself.
</p>
<p>
 When ranking the universities, the we looked at the information collected under each
 of the ranking Criteria, and assigned relative scores to the total number of points
 assigned to each of the Criteria. The rank is calculated by taking average of the
 cumulative sum of scores achieved by that university(dividing with the number of users
 voted the university).
</p>
