<h2 class="title">Welcome to our news room:</h2>
<br>
<h1>
News of the week:
</h1>	
<hr>
<?php foreach($this->newsinfo as $newsshow) : ?>	
						<p><a href="<?php echo $this->url(array('controller'=>'news','action'=>'details', 'news_id'=>$newsshow['news_id']));?>"><?php echo $this->escape($newsshow['title']); ?></a></p>
						
<?php endforeach; ?>

<div class="post">
 <p class="links"> <?php  echo $this->newsinfo; ?> </p>
</div>
<br/>
<br/>
<hr/>
<h1>
<p><a href="<?php echo $this->url(array('controller'=>'newsarc','action'=>'index'));?>"><?php echo "Go to news Archives"; ?></a></p>
</h1>

