
      <?php if ($this->pageCount): ?>
      <!-- First page link -->
      <?php if (isset($this->previous)): ?>

        <a href="<?php echo $this->url(array('page' => $this->first)); ?>">

          First
        </a> |
      <?php else: ?>
        <span class="posted">First</span> |
      <?php endif; ?>
       
      <!-- Previous page link -->
      <?php if (isset($this->previous)): ?>
        <a href="<?php echo $this->url(array('page' => $this->previous)); ?>">
          &lt; Previous
        </a> |
      <?php else: ?>
        <span class="posted">&lt; Previous</span> |
      <?php endif; ?>
       
      <!-- Next page link -->
      <?php if (isset($this->next)): ?>
        <a href="<?php echo $this->url(array('page' => $this->next)); ?>">
          Next &gt;
        </a> |
      <?php else: ?>
        <span class="posted">Next &gt;</span> |
      <?php endif; ?>
      <!-- Last page link -->
      <?php if (isset($this->next)): ?>
        <a href="<?php echo $this->url(array('page' => $this->last)); ?>">
          Last
        </a>
      <?php else: ?>
        <span class="posted">Last</span>
      <?php endif; ?>
      <?php endif; ?>