<h2>Contact Us</h2>
<hr>
<p>If you wish u can mail us at <b>uniinfo@yahoo.com</b>, or you can write us just here. We are waiting
for your nice and valuable suggestion to develop our services.</p>
<p> Thank you for your co-operation.</p>
<h1>Posts:</h1>
<hr>
<?php foreach($this->contacts as $contact) : ?>
			<div class="comment">
			
				<p class="meta"><span class="posted">Name: <?php echo $this->escape($contact['FirstName']); ?></span></p>
				<div class="entry">
						<p>	<?php echo $contact['contacttext']; ?> </p>
				</div>
			</div>	
<?php endforeach; ?>
<div class="post">
 <p class="links"> <?php  echo $this->contacts; ?> </p>
</div>
<br>
<br>
<h1>Post here:</h1>
<hr>
<?php echo $this->form; ?>