<h2>About Us</h2>
<hr>
<p>
uniinfo.com is the Internet's largest site for the collaboration of students from all over the world, with student-generated university ranking and professors ratings. Each year, millions of college students use the site to take their descission for heigher studies.
</p>
<p class="links"><a href="<?php echo $this->url(array('controller'=>'aboutus','action'=>'contactus'));?>">Contact us</a></p>