<h1>Change Your Password :</h1>
<hr>
<br>
<h3> <?php echo $this->error; ?></h3>
<br>
<p> To better protect your account, make sure that your password is memorable for you but difficult for others to guess. Do not share your password with anyone, and never use the same password that you've used in the past. For security purposes, your new password must be a minimum of six characters long. A strong password contains a combination of uppercase and lowercase letters (remember that your password is case sensitive), numbers and no special character is allowed.
</p>
<?php echo $this->form; ?>