<h2>Find what is needed</h2>
<p>Here you can search different users to see his profile details, as well as teachers from all over the world.
More over you can find different universities under some criteria.</p>
<p><a href="<?php echo $this->url(array('controller'=>'search','action'=>'srchuser'));?>">Find user</a></p>
<p><a href="<?php echo $this->url(array('controller'=>'search','action'=>'srchteacher'));?>">Find Teachers</a></p>
<p><a href="<?php echo $this->url(array('controller'=>'unisearch','action'=>'index'));?>">Find University</a></p>