<h2>Search User:</h2>
<hr>
<?php
	echo $this->form;
?>
<?php if($this->posted == 1) { ?>
<h2>Search Result is here:</h2>
<hr>

<?php
if($this->error != null)
{
	echo $this->error;
}
else
{
	
?>
<h1>Probable Names</h1>
<br/>
<?php foreach($this->users as $user) : ?>

	<div class="comment">	
		<p class="meta"><span class="posted"><a href="<?php echo $this->url(array('controller'=>'profile','action'=>'userdetails','user_id'=>$user['user_id']));?>"><img border="0" src="<?php echo 'http://localhost/sdproject/application/picture/thumbnails/_'.$user['email'].'.png'; ?>" alt="" width="50" height="50" /><?php echo " ".$this->escape($user['FirstName'])." ".$this->escape($user['LastName']); ?></a></span></p>
	</div>
	<br/>
<?php endforeach; ?>
<?php } ?>
<?php } ?>

<div class="post">
 <p class="links"> <?php  echo $this->users;  ?> </p>
</div>

	