<h2>Search User:</h2>
<hr>
<?php
	echo $this->form;
?>
<?php if($this->posted == 1) { ?>
<h2>Search Result is here:</h2>
<hr>

<?php
if($this->error!= null)
{
	echo $this->error;
}
else
{
	
?>
<h1>Probable Names</h1>
<br/>
<?php foreach($this->members as $member) : ?>	
	<p><a href="<?php echo $this->url(array('controller'=>'facultymember','action'=>'details','facultymember_id'=>$member['FacultyMemberID']));?>"><?php echo $this->escape($member['Name']); ?></a></p>
<?php endforeach; ?>
<?php } ?>
<?php } ?>

<div class="post">
 <p class="links"> <?php  echo $this->members;  ?> </p>
</div>

	