<h2 class="title">Find your university here:</h2>
<hr>
<p><a href="<?php echo $this->url(array('controller'=>'university','action'=>'index'));?>"><?php echo "Show all universities"; ?></a></p>
<p><a href="<?php echo $this->url(array('controller'=>'unisearch','action'=>'uniname'));?>"><?php echo "Search by name"; ?></a></p>
<p><a href="<?php echo $this->url(array('controller'=>'unisearch','action'=>'unicountry'));?>"><?php echo "Search by Country name"; ?></a></p>
<p><a href="<?php echo $this->url(array('controller'=>'unisearch','action'=>'advancedsrch'));?>"><?php echo "Advanced Search"; ?></a></p>
<p>
Here you can search any university from our database. All the information is provided, maintained,updated by University authority and 
we are not responsible for any informaition displayed here.
</p>