<h2>Search your University:</h2>
<hr>
<?php
	echo $this->form;
?>
<?php if($this->posted == 1) { ?>
<h2>Search Result is here:</h2>
<hr>

<?php
if($this->unis == null)
{
	echo "Sorry there is no university of this country exists in our database";
}
else
{
?>
<table border = 1>
<tr>
<th><h3>University name</h3></th>
<th><h3>Country</h3></th>
<th><h3>University Ranking</h3></th>
</tr>
<?php foreach($this->unis as $uni) : ?>
		<tr>
		<td><a href="<?php echo $this->url(array('controller'=>'university','action'=>'unidetails','uni_id'=>$uni['university_id']));?>"><?php echo $this->escape($uni['uni_name']); ?></a></td> 
		<td><?php echo $this->escape($uni[uni_country]);?></td>
		<td><?php echo $this->escape($uni[uni_rank]);?></td>
		</tr>
<?php endforeach; ?>
</table>
<?php } ?>

<?php } ?>
<div class="post">
 <p class="links"> <?php  echo $this->unis;  ?> </p>
</div>

	