<h2>Upload Image</h2>
<hr/>
<h3>Upload a photo of yourself that you like to use as your profile picture.</h3>
<?php echo $this->form; ?>
<br/>
By clicking Upload Photo, I certify that I have the right to distribute this picture and that it does not violate the uniinfo.com 
<a href="<?php echo $this->url(array('controller'=>'image','action'=>'policy'));?>">Photo Policy</a>.
<br/>
<br/>
<b>If photo upload fails, try again with a smaller photo.</b>
