<h2>Uniinfo Photo Policy</h2>
<hr/>
<p>Not all types of photos are suitable for use on uniinfo. Here are the guidelines:</p>

   1. Submitted photos should be of high-quality, clear and current. You may be creative with your photos as long as it does not violate this policy.
   <br/>
   <br/>
   2. Please do not upload photos of children alone, or images of yourself as a child. Photos containing only animals are not appropriate, but you may use photos of yourself together with pets.
	<br/>
	<br/>
   3. uniinfo is not able to investigate or confirm the copyright or ownership of artwork or other uploaded images, so please do not upload files that do not contain photos of yourself. Any photo containing cartoons, comics, celebrities, nudity, pornography, sexually explicit images or any copyrighted image (unless you own the copyright) is not permitted. Photos of celebrities and cartoon or comic images are generally copyrighted by the owner.
   <br/>
   <br/>
   4. Submitted photos are limited to a size of 2MB and must be in one of the following formats: GIF, JPG, or PNG.
   <br/>
   <br/>
   5. For security and privacy reasons, please do not upload any photos that contain contact information such as names, phone numbers, email addresses, or web site URLs.
	<br/>
   <br/>
<p>If you see any photos on uniinfo that do not conform to this policy, please email help@uniinfo.com</p>